CREATE TABLE CONFIG_FRONTEND (
    OID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SCRIPT_NAME VARCHAR(255) NOT NULL,
    EXPOSED_MODULE VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    ROUTE_PATH VARCHAR(255) NOT NULL,
    NG_MODULE_NAME VARCHAR(255) NOT NULL,
    VERSION_PRINCIPAL INTEGER NOT NULL,
    VERSION_MAJOR INTEGER NOT NULL,
    VERSION_MINOR INTEGER,
    CUSTOM_HOST VARCHAR(255)
);